version: '3'
services:
  julia:
    image: sunaasobijl
    container_name: sunaasobijl-julia
    volumes:
      - ./:/workspace/Sunaasobi.jl
    working_dir: /workspace/Sunaasobi.jl
    command: julia --project=/workspace/Sunaasobi.jl
  web:
    image: sunaasobijl
    container_name: sunaasobijl-packagedocs
    volumes:
      - ./:/workspace/Sunaasobi.jl
    working_dir: /workspace/Sunaasobi.jl
    ports:
      - "8000:8000"
    command: make web
